---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 12.4.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 2.1.0
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 10.5.0
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
    version: 1.10.6

roles:
  - name: githubixx.ansible_role_wireguard
    version: 19.1.0
