collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 10.2.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 2.0.0
  - name: lablabs.wireguard
    source: https://galaxy.ansible.com
    version: 0.3.3
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 10.2.0
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
    version: 1.10.6
