collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 11.4.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 2.1.0
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 10.3.1
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
    version: 1.10.6

roles:
  - name: githubixx.wireguard
    version: 23.1.0
